import os

EXCELLA_SLACK_USERS = {
    "Josh Cohen": 49,
    "Nick Bristow": 48,
    "Joe Hunt": 47,
    "Andrew Eason": 46,
    "Andy Whitley": 45,
    "Hugh Gardiner": 44,
    "Daniel Herndon": 43,
    "Griffin Norris": 42,
    "Matt Acors": 41,
    "Andrew Jarding": 40,
    "Angela Lu": 39,
    "Adam Parker": 38,
    "Brian Palladino": 37,
    "Cameron Ivey": 36,
    "Cara Peters": 35,
    "Chris Arsenault": 34,
    "Chris Petro": 33,
    "Colyn Irvine": 32,
    "Dane Weber": 31,
    "David Chang": 30,
    "Glenn Espinosa": 29,
    "Hank Ritchie": 28,
    "Iksu Oh": 27,
    "Jay Danielian": 26,
    "Jen Pengelly": 25,
    "Joan Nelson": 24,
    "Josh Dorothy": 23,
    "Drew Nickerson": 22,
    "Khoi Le": 21,
    "Mayowa Aladeojebi": 20,
    "Mark Koenig": 10,
    "Paul Schneider": 11,
    "Zack Ayers": 12
}