import os

EXCELLA_SLACK_USERS = {
    "Josh Cohen": 44,
    "Nick Bristow": 22,
    "Joe Hunt": 24,
    "Andrew Eason": 29,
    "Andy Whitley": 28,
    "Hugh Gardiner": 35,
    "Daniel Herndon": 47,
    "Griffin Norris": 34,
    "Matt Acors": 11,
    "Andrew Jarding": 9,
    "Angela Lu": 30,
    "Adam Parker": 49,
    "Brian Palladino": 27,
    "Cameron Ivey": 31,
    "Cara Peters": 48,
    "Chris Arsenault": 10,
    "Chris Petro": 32,
    "Colyn Irvine": 26,
    "Dane Weber": 33,
    "David Chang": 46,
    "Glenn Espinosa": 45,
    "Hank Ritchie": 8,
    "Iksu Oh": 36,
    "Jay Danielian": 37,
    "Jen Pengelly": 12,
    "Joan Nelson": 7,
    "Josh Dorothy": 43,
    "Drew Nickerson": 25,
    "Khoi Le": 42,
    "Mayowa Aladeojebi": 23,
    "Mark Koenig": 41,
    "Paul Schneider": 40,
    "Zack Ayers": 21
}